name: CD
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to release
        required: true
jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update package json
        run: yq -i '.version="${{ github.event.inputs.version }}"' package.json

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create release on GitHub
        run: |
          gh release create v${{ github.event.inputs.version }} \
          --generate-notes -t "${{ github.event.repository.name }} ${{ github.event.inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
